# -*- coding: utf-8 -*-
"""ConneR and the A.R.C. Markland-N.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Io0OLrMw60E6v2o1hYbhJoLI377rJHqG
"""

ans=[]
val_ans=[]
for i in range(int(input())):
  n,s,k=input().split()
  n=int(n)
  s=int(s)
  k=int(k)

  arr=list(map(int,input().split()))
  for i in range(1,n+1):
    if i not in arr:
      ans.append(i)

  val=min(ans, key=lambda x:abs(x-s))
  print(abs(val-s))
  val_ans.append((abs(val-s)))
  
for i in val_ans:
  
  print(i,end='\n')

